### ISSUE TITLE
Missing gemspec

### ISSUE THREAD

**Issue by cover** [derailed/ziya#1]
Hi, I'm migrating to bundler and I've installed ziya using the gem on rubygems. Unfortunately you've forgotten to include the gemfile into the gem in order to let bundler know the dependencies to install (logging and color). I've "fixed" it including in the gemfile the two gems, but it would be better managed by the gemfile
Thanks

**Comment by derailed** [comment]
Hi - Thanks for the feedback! I have updated the gem. Please try it again and report back if I've missed something.
